# https://okteto.com/docs/cloud/github-actions/index.html

on: [push]

name: deploy

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        name: hbstarjason
    
    - name: "Build"
      uses: okteto/build@master
      with:
        tag: registry.cloud.okteto.net/hbstarjason/pipeline-craft:${{ github.sha }}

    - name: "Deploy application"
      uses: okteto/apply@master
      with:
        manifest: okteto.yml

    - name: "Push changes"
      uses: okteto/push@master
      with:
        namespace: hbstarjason
        name: pipeline-craft    